# -*- coding: utf-8 -*-
"""Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggVlzR5fAEvDUpSKtK_wztCBkIwleWDG
"""

# Install necessary libraries
!pip install diffusers transformers accelerate torch --quiet
!pip install invisible_watermark transformers accelerate safetensors --quiet
!pip install ftfy==6.1.1 # Install a specific version of ftfy for better compatibility if needed

import torch
from diffusers import DiffusionPipeline
from IPython.display import display

# Load the Stable Diffusion model
# Using safety_checker=None to potentially avoid compatibility issues with it

# Load the base SDXL model for the initial generation
# Enable sequential CPU offloading for maximum memory saving
base = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
)
base.enable_sequential_cpu_offload()


# Load the refiner model for the finishing touches
# Enable sequential CPU offloading for the refiner as well
refiner = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    text_encoder_2=base.text_encoder_2,
    vae=base.vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
refiner.enable_sequential_cpu_offload()

print("SDXL models are loaded and ready using sequential CPU offloading.")

prompt = "In the style of Van Gogh — starry sky over a peaceful village, oil painting brush texture"

print(f"\n Generating image for prompt: '{prompt}'")

# --- Step 4: Generate and Refine the Image ---
# We run the base model first, then pass its output to the refiner.
# We set `output_type="latent"` to pass the raw data to the refiner without saving an intermediate image.

# Enable attention slicing and VAE slicing for memory efficiency
base.enable_attention_slicing()
base.enable_vae_slicing()
refiner.enable_attention_slicing()
refiner.enable_vae_slicing()


image_latents = base(
    prompt=prompt,
    output_type="latent",
).images

# The refiner model adds the final high-quality details.
image = refiner(
    prompt=prompt,
    image=image_latents,
).images[0]

print(" Image generated and refined successfully!")
display(image)